use OTRS_DB_RESTAURANT;
create table RESTAURANT (
	ID varchar(255) NOT NULL PRIMARY KEY,
    FULLNAME varchar(255),
    IS_MODIFIED bit NOT NULL,
    ADDRESS text,
    TABLE_ID INT
);

use OTRS_DB_RESTAURANT;
CREATE TABLE RESTAURANT_TABLE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME varchar(255),
    IS_MODIFIED bit NOT NULL,
    CAPACITY INT
);

use OTRS_DB_RESTAURANT;
CREATE TABLE BOOKING (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME varchar(255),
    IS_MODIFIED bit NOT NULL,
    RESTAUANT_ID INT,
    USER_ID INT,
    DATE date,
    TIME datetime,
    TABLE_ID INT
);

use OTRS_DB_RESTAURANT;
CREATE TABLE BOOKING (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME varchar(255),
    IS_MODIFIED bit NOT NULL,
    RESTAUANT_ID INT,
    USER_ID INT,
    DATE date,
    TIME datetime,
    TABLE_ID INT
);

use OTRS_DB_RESTAURANT;
create table USERS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME varchar(255),
    IS_MODIFIED bit NOT NULL,
	USERNAME varchar (50) not null,
	PASSWORD varchar (100) not null,
	ENABLED boolean not null,
	EMAIL varchar(50),
    ADDRESS TEXT,
    CITY TEXT,
    PHONE_NO TEXT,
    UNIQUE (USERNAME)
);

use OTRS_DB_RESTAURANT;
insert into RESTAURANT (ID, FULLNAME, ADDRESS, IS_MODIFIED) values ('1', 'Magic Food', 
'Don Mueng Airport', false);
insert into RESTAURANT (ID, FULLNAME, ADDRESS, IS_MODIFIED) values ('10', 'Fuji Restaurant', 'Future Park Rangsit', 
false);

insert into OTRS_DB_RESTAURANT.BOOKING (BOOKING.ID, BOOKING.FULLNAME, BOOKING.IS_MODIFIED, 
BOOKING.RESTAUANT_ID, BOOKING.USER_ID, BOOKING.DATE, BOOKING.TIME, BOOKING.TABLE_ID) values
(1, 'TEST_1', 0, 1, 1, '2019-09-29', now(), 1);
insert into OTRS_DB_RESTAURANT.BOOKING (BOOKING.ID, BOOKING.FULLNAME, BOOKING.IS_MODIFIED, 
BOOKING.RESTAUANT_ID, BOOKING.USER_ID, BOOKING.DATE, BOOKING.TIME, BOOKING.TABLE_ID) values
(5, 'TEST_BOOKING_NAME_2', 0, 1, 1, '2019-09-29', now(), 1);

INSERT INTO USERS (USERS.ID, USERS.FULLNAME, USERS.IS_MODIFIED, USERS.USERNAME, USERS.PASSWORD, 
USERS.ENABLED, USERS.EMAIL, USERS.ADDRESS, USERS.CITY, USERS.PHONE_NO) values (1, 'JOHN SMITH', 0, 
'JOHN_SMITH', 'password', 1, 'john.sm@gmail.com', '285', 'rangsit', '0982545769')
