spring:
   application:
      name: booking-service
   datasource:
      url: jdbc:mysql://localhost:3306/OTRS_DB_RESTAURANT?useSSL=true
      username: root
      password:
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   messsage:
      fallback-to-system-locale: false
      
server:
  port: 2223
      
logging:
   level:
      #org.springframework.web: DEBUG
      #guru.springframework.controllers: DEBUG
      #org.hibernate: DEBUG
      root: DEBUG





